### ISSUE TITLE
Subject: Inquiry About src/data_management.R in spatialepi_biostats Repository

### ISSUE THREAD

**Issue by 777brain** [nicolofp/spatialepi_biostats#1]
Dear Nicolo' Foppa Pedretti,
I hope this message finds you well. My name is tony, and I am currently working on a project related to spatial epidemiology. I came across your GitHub repository spatialepi_biostats, and I am very interested in understanding and potentially utilizing your work.
I noticed in the src/data_management.R file, there is a reference to an Amazon key, and I was wondering if you could provide some guidance on how this should be handled. Is this something I need to generate myself for my own usage, or is there a specific process or set of credentials that you recommend?
I greatly appreciate any insight you can offer. Understanding this will be a significant help in moving my project forward.
Thank you for your time and your contributions to the community.
Best regards,
tony

**Comment by nicolofp** [comment]
Hi Tony,
in that R file I upload some data to my AWS account. That file mainly contains the configuration on my account. Here some useful resources that you can use to set up the connection between R and your AWS S3 account: 

+ https://cran.r-project.org/web/packages/aws.s3/readme/README.html
+ https://blog.djnavarro.net/posts/2022-03-17_using-aws-s3-in-r/

If you need the file that I used I can upload in a new folder `data` the file that I used for my analysis.
Please let me know if it works for you.

Thanks,
Nicolo'

**Comment by 777brain** [comment]
Dear Nicolo' Foppa Pedretti,
I hope this message finds you well. My name is tony, and I am currently engaging in research that closely aligns with your work in the spatialepi_biostats repository on GitHub, which I find insightful and extremely relevant to my field of study.
As I was exploring the repository, I noticed that the results.rds and results-sp.rds files seem to be empty, and I was wondering if this was intentional or if there might have been an issue with the file upload. These results files appear to be critical for understanding the full context and outcome of your work.
If possible, could you please clarify whether these files are supposed to contain analysis results? If they are essential for replicating your research outcomes or understanding your analysis pipeline, I would be grateful if you could provide any available versions of these files or further insights on how to generate them from the provided datasets and scripts.
Your assistance would greatly enhance my understanding of your applied methodologies and contribute significantly to my research progress.
Thank you very much for your time and for sharing your valuable work with the community. I am looking forward to your response.
Best regards,
tony

**Comment by 777brain** [comment]
Dear Nicolo' Foppa Pedretti,
I was wondering if this was intentional or if there might have been an issue with the file upload. These results files appear to be critical for understanding the full context and outcome of your work.
If possible, could you please clarify whether these files are supposed to contain analysis results? If they are essential for replicating your research outcomes or understanding your analysis pipeline, I would be grateful if you could provide any available versions of these files or further insights on how to generate them from the provided datasets and scripts.
Your assistance would greatly enhance my understanding of your applied methodologies and contribute significantly to my research progress.
Thank you very much for your time and for sharing your valuable work with the community. I am looking forward to your response.
Best regards,
tony

**Comment by 777brain** [comment]
Dear Nicolò,
I am currently reviewing the scripts within your spatialepi_biostats repository, specifically those related to pollutants (pollutants.R), health (health.R), and data management (management.R). As part of my research work, I am trying to comprehend the functionality and potential applications of each script.
Would you be willing to provide a brief overview or documentation of the core functionalities and intended use-cases for these scripts? This information would be immensely helpful for me to accurately interpret the code and potentially apply it in my own work regarding spatial epidemiology.
Thank you for considering my request, and for your contributions to the scientific community.
Best regards,
tony

**Comment by nicolofp** [comment]
Hi Tony,
it seems the `results.rds` files are not empty. Were you able to open them? 
This repository is not complete yet, as soon as possible I will create readme file and notebook with all the pipeline that I used.
In the meanwhile you should be able to run `pollution_dara.R` first and `spatial_analysis.R` after that. In the `spatial_data.R` code you can un-comment the line where I run the Stan code and avoid the loading of my results but create your own.

Please let me know if it's clear and forgive me for those messy codes.
Thanks,
Nicolo'

**Comment by 777brain** [comment]
Dear Nicolo' Foppa Pedretti,
 it's clear and thank you for you
Best regards,
tony

> Hi Tony, it seems the files are not empty. Were you able to open them? This repository is not complete yet, as soon as possible I will create readme file and notebook with all the pipeline that I used. In the meanwhile you should be able to run first and after that. In the code you can un-comment the line where I run the Stan code and avoid the loading of my results but create your own.`results.rds``pollution_dara.R``spatial_analysis.R``spatial_data.R`
> 
> Please let me know if it's clear and forgive me for those messy codes. Thanks, Nicolo'

hi Nicolo',
Thank you for your prompt response. I was indeed able to open the files.Your guidance is clear, and there is no need to apologize for the state of the codes, I appreciate you sharing your work-in-progress.Please forgive my numerous inquiries – I am quite new to this area of research and every bit of information is extremely valuable to me as I navigate through the learning process.
Your assistance and patience with my queries are truly appreciated, and they've made a significant impact on my understanding of the subject. Thank you once again, and I eagerly await the repository updates.

Best regards,
Tony

**Comment by nicolofp** [comment]
I'm happy that you found useful this experimental code. As you can see from the files I planned to extend the methods including some API code for air pollution and water pollution. I hope to be able to complete those projects soon. 
Please let me know if there are other pending issues or if I can close this one.

Thanks,
Nicolo'
